---
# Development Inventory for CF-DEMO-REPO
# This inventory is for testing and development purposes

all:
  children:
    # Localhost for Cloudflare API operations
    cloudflare_controllers:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
          
    # Development zones
    development_zones:
      hosts:
        zone_dev:
          cloudflare_zone_name: "dev.example.com"
          cloudflare_zone_id: "your-dev-zone-id"
          environment: "development"
      
      vars:
        # Development-specific Cloudflare settings
        cloudflare_ssl_mode: "flexible"
        cloudflare_security_level: "medium"
        cloudflare_cache_level: "basic"
        cloudflare_development_mode: true
        cloudflare_min_tls_version: "1.0"
